allowBuilds:
  '@vercel/speed-insights': true
  bufferutil: true
  core-js: true
  core-js-pure: true
  es5-ext: true
  esbuild: true
  fsevents: true
  keccak: true
  postinstall-postinstall: true
  secp256k1: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
  web3: true
  web3-bzz: true
  web3-shh: true

overrides:
  'elliptic': '^6.6.1'
  'pbkdf2': '^3.1.5'
  'form-data': '^4.0.4'
