name: 🐛 Bug Report
description: This form is to report a bug
labels: ['type:bug']
body:
    - type: markdown
      attributes:
          value: |
              Thank you for taking your precious time to file an issue!

              We know that your time is precious, but the first step in fixing this issue is to understand the issue. Taking some extra time to ensure that we are able to reproduce the issue will help us significantly in resolving the issue.
    - type: dropdown
      id: network
      attributes:
          label: Which network is that happening?
          description: Select the appropriate chains.
          multiple: true
          options:
              - Mainnet
              - Sepolia
      validations:
          required: true
    - type: dropdown
      id: app
      attributes:
          label: Which Explorer is that Bug happening?
          description: If this issue is occurring on more than 1 App, select the appropriate Apps.
          multiple: true
          options:
              - Staking
              - Rollups
      validations:
          required: true
    - type: textarea
      id: expected-behaviour
      attributes:
          label: 🙂 Expected behavior
          description: What is expected to happen?
      validations:
          required: true
    - type: textarea
      id: actual-behaviour
      attributes:
          label: 🫠 Actual behavior
          description: What is happening instead?
      validations:
          required: true
    - type: textarea
      id: minimal-test-case
      attributes:
          label: 🧪 Minimal test case
          description: |
              Please describe a minimal test case that demonstrates the bug. 
              If possible, this should be an automated test.
      validations:
          required: true
    - type: textarea
      id: extra-information
      attributes:
          label: 📄 Extra information
          description: Anything else that might be relevant?
