// Copyright (C) 2022 Cartesi Pte. Ltd.

// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.

// This program is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
// PARTICULAR PURPOSE. See the GNU General Public License for more details.

import { gql } from '@apollo/client';

export type EnsDomain = {
    __typename?: 'Domain';
    name?: string | null;
    labelName?: string | null;
    resolvedAddress?: { __typename?: 'Account'; id: string } | null;
};

export type DomainAlias = `addr${string}`;

export type GetAliasedEnsDomainsQuery = Record<DomainAlias, EnsDomain[]>;

/**
 *
 * @summary Generates an alias for a given address to be used in the aliased GraphQL query.
 * @description
 * The alias is generated by prefixing the address with "addr" and replacing any non-alphanumeric characters with underscores.
 * This ensures that the alias is a valid GraphQL field name.
 * @param address
 * @returns
 */
export const getDomainAlias = (address: string): DomainAlias =>
    `addr${address.toLowerCase().replace(/[^a-z0-9_]/g, '_')}`;

/**
 * @summary Dynamically generates aliased GraphQL query to fetch the latest ENS domain per Address passed.
 * @description One address may have multiple domain entries through time.
 * Due to constraints in response size it may cause domains to not be included in the response.
 * Nonetheless, we want only the latest domain name.
 * By aliasing the query there is a perceptible improvement in response time as the database query
 * is more efficient due to not using the "in" operator and instead using multiple "where" clauses with equality checks.
 *
 * @param addresses
 * @returns
 */
export const buildAliasedEnsDomainsQuery = (addresses: string[]) => {
    const fields = addresses
        .map((address) => {
            const alias = getDomainAlias(address);
            return `
                ${alias}: domains(
                    first: 1
                    where: { resolvedAddress: "${address}" }
                    orderBy: createdAt
                    orderDirection: desc
                ) {                    
                    labelName
                    name
                    resolvedAddress {
                        id
                    }
                }
            `;
        })
        .join('\n');

    return gql`
        query getDomains {
            ${fields}
        }
    `;
};
