name: Docker Packaging [Rollups]
on:
    pull_request:
        paths:
            - 'apps/rollups/**'
            - 'packages/**'
    push:
        paths:
            - 'apps/rollups/**'
            - 'packages/**'
            - './github/workflows/docker-rollups.yml'
        branches:
            - main
        tags:
            - rollups@*

permissions:
    contents: read
    packages: write
    id-token: write

concurrency:
    group: ${{github.workflow}}-${{github.ref_name}}
    cancel-in-progress: true

env:
    image_name: rollups-explorer
    push_to_dockerhub: ${{startsWith(github.ref, 'refs/tags/rollups@')}}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'yarn'

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Code format check
              run: yarn format:check

            - name: Linting
              run: yarn lint

            - name: Run Tests
              run: yarn test

            - name: Set Up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set Up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2

            - name: Docker Meta
              id: docker_meta
              uses: docker/metadata-action@v4
              with:
                  images: |
                      name=ghcr.io/${{ github.repository_owner }}/${{ env.image_name }}
                      name=docker.io/${{ github.repository_owner }}/${{ env.image_name }},enable=${{ env.push_to_dockerhub }}
                  tags: |
                      type=match,pattern=rollups@(.*),group=1
                      type=edge,branch=${{github.event.repository.default_branch}},enable=${{github.event.repository.default_branch == github.ref_name}}
                      type=ref,event=pr
                  labels: |
                      org.opencontainers.image.title=Rollups Explorer
                      org.opencontainers.image.description=Web app to interact with DApps

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              if: ${{ env.push_to_dockerhub == 'true'}}
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build & Push Docker Image
              id: docker_build
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: docker/Dockerfile-rollups
                  platforms: linux/amd64,linux/arm64
                  tags: ${{ steps.docker_meta.outputs.tags }}
                  labels: ${{ steps.docker_meta.outputs.labels }}
                  builder: ${{ steps.buildx.outputs.name }}
                  push: true
